Repository orion-rs/orion, pull requests merged in 2019-07, with the labels that each got.

#78 Document newtype PartialEq usage
  src/typedefs.rs
Labels: documentation

#80 Switch to stable rustfmt
  .rustfmt.toml
  .travis.yml
  src/endianness.rs
  src/errors/mod.rs
  src/hash.rs
  src/hazardous/aead/chacha20poly1305.rs
  src/hazardous/aead/xchacha20poly1305.rs
  src/hazardous/hash/sha512.rs
  src/hazardous/stream/chacha20.rs
Labels: improvement

#79 Reduce calls to memcpy in SHA512 and BLAKE2b
  src/hazardous/hash/blake2b.rs
  src/hazardous/hash/sha512.rs
Labels: improvement

#81 Remove use of deprecated getrandom errors
  Cargo.toml
  src/errors/mod.rs
Labels: bugfix
