Repository orion-rs/orion, pull requests merged in 2019-10, with the labels that each got.

#102 Drop needless bool in constant-time comparison/verification functions
  src/auth.rs
  src/hazardous/hash/blake2b.rs
  src/hazardous/kdf/hkdf.rs
  src/hazardous/kdf/pbkdf2.rs
  src/hazardous/mac/hmac.rs
  src/hazardous/mac/poly1305.rs
  src/kdf.rs
  src/pwhash.rs
  src/util/mod.rs
  tests/kdf/custom_pbkdf2.rs
  tests/mac/mod.rs
Labels: Breaking change, improvement

#96 Test framework for common interfaces
  src/aead.rs
  src/auth.rs
  src/endianness.rs
  src/hash.rs
  src/hazardous/aead/chacha20poly1305.rs
  src/hazardous/aead/xchacha20poly1305.rs
  src/hazardous/hash/blake2b.rs
  src/hazardous/hash/sha512.rs
  src/hazardous/kdf/pbkdf2.rs
  src/hazardous/mac/hmac.rs
  src/hazardous/mac/poly1305.rs
  src/hazardous/stream/chacha20.rs
  src/hazardous/stream/xchacha20.rs
  src/kdf.rs
  src/lib.rs
  src/pwhash.rs
  src/test_framework/aead_interface.rs
  src/test_framework/incremental_interface.rs
  src/test_framework/mod.rs
  src/test_framework/streamcipher_interface.rs
  src/typedefs.rs
  tests/aead/mod.rs
  tests/kdf/mod.rs
  tests/mod.rs
  tests/stream/mod.rs
  tests/stream/other_chacha20.rs
  tests/stream/rfc_chacha20.rs
  tests/stream/rfc_xchacha20.rs
Labels: improvement, testing

#88 Change high-level auth to a wrapper around keyed Blake2b
  src/auth.rs
  src/hazardous/hash/blake2b.rs
  src/hltypes.rs
  src/lib.rs
Labels: Breaking change

#99 XChaCha20Poly1305 streaming encryption
  src/hazardous/aead/chacha20poly1305.rs
  src/hazardous/aead/mod.rs
  src/hazardous/aead/streaming.rs
  src/hazardous/aead/xchacha20poly1305.rs
  src/hazardous/stream/chacha20.rs
  src/hazardous/stream/xchacha20.rs
  tests/test_generation/generate_secret_stream_test_values.c
Labels: new feature

#105 Test and document MSRV
  .travis.yml
  README.md
Labels: documentation

#107 Public API changes to increase familiarity
  benches/bench.rs
  src/auth.rs
  src/hazardous/aead/streaming.rs
  src/hazardous/hash/blake2b.rs
  src/hazardous/hash/sha512.rs
  src/hazardous/mac/hmac.rs
  src/hazardous/mac/poly1305.rs
  src/kdf.rs
  src/typedefs.rs
  tests/hash/mod.rs
  tests/mac/mod.rs
Labels: Breaking change, usability
