Repository orion-rs/orion, pull requests merged in 2021-03, with the labels that each got.

#181 Cleanup of SHA2 implementations
  .github/workflows/lints.yml
  .github/workflows/temp_nightly_tests.yml
  src/hazardous/hash/sha2/mod.rs
  src/hazardous/hash/sha2/sha256.rs
  src/hazardous/hash/sha2/sha384.rs
  src/hazardous/hash/sha2/sha512.rs
  src/hazardous/kdf/hkdf.rs
  src/hazardous/kdf/pbkdf2.rs
  src/hazardous/mac/hmac.rs
  src/util/endianness.rs
Labels: improvement

#183 Update benchmarks to include new SHA2 variants for SHA, HMAC, HKDF and PBKDF2
  benches/bench.rs
Labels: testing

#184 Remove hkdf::verify and orion::kdf::derive_key_verify()
  src/hazardous/kdf/hkdf.rs
  src/high_level/kdf.rs
  tests/kdf/mod.rs
Labels: breaking change

#185 Use intra-doc links and other small documentation improvements
  src/hazardous/aead/chacha20poly1305.rs
  src/hazardous/aead/streaming.rs
  src/hazardous/aead/xchacha20poly1305.rs
  src/hazardous/hash/blake2b.rs
  src/hazardous/hash/sha2/sha256.rs
  src/hazardous/hash/sha2/sha384.rs
  src/hazardous/hash/sha2/sha512.rs
  src/hazardous/kdf/argon2i.rs
  src/hazardous/kdf/hkdf.rs
  src/hazardous/kdf/pbkdf2.rs
  src/hazardous/mac/hmac.rs
  src/hazardous/mac/poly1305.rs
  src/hazardous/stream/chacha20.rs
  src/hazardous/stream/xchacha20.rs
  src/high_level/aead.rs
  src/high_level/auth.rs
  src/high_level/hash.rs
  src/high_level/hltypes.rs
  src/high_level/kdf.rs
  src/high_level/pwhash.rs
  src/lib.rs
  src/util/mod.rs
Labels: documentation

#187 KDF output buffer zeroization documentation
  src/hazardous/kdf/argon2i.rs
  src/hazardous/kdf/pbkdf2.rs
Labels: documentation

#189 Use constant-time Base64 in `pwhash::PasswordHash`
  Cargo.toml
  src/errors.rs
  src/high_level/pwhash.rs
Labels: dependencies, security

#190 clippy: Use lowercase acronyms for StreamTag enum
  src/hazardous/aead/streaming.rs
  src/high_level/aead.rs
Labels: breaking change, improvement

#194 remove erroneous non-constant-time warning
  src/high_level/pwhash.rs
Labels: documentation

#195 Add missing doc updates to `isize::MAX` length restrictions
  src/high_level/hltypes.rs
  src/high_level/kdf.rs
  src/high_level/pwhash.rs
Labels: documentation
