Repository orion-rs/orion, pull requests merged in 2021-11, with the labels that each got.

#241 Add benchmarks for X25519
  benches/bench.rs
Labels: testing

#240 Use `doc_cfg` to render feature badges for feature-gated functionality
  Cargo.toml
  src/high_level/aead.rs
  src/high_level/auth.rs
  src/high_level/hash.rs
  src/high_level/kdf.rs
  src/high_level/kex.rs
  src/high_level/pwhash.rs
  src/lib.rs
Labels: documentation

#242 New crate features wiki page
  README.md
Labels: documentation

#209 Separate interfaces for BLAKE2b in keyed and non-keyed mode
  src/hazardous/hash/blake2/blake2b.rs
  src/hazardous/hash/blake2/mod.rs
  src/hazardous/hash/blake2b.rs
  src/hazardous/hash/mod.rs
  src/hazardous/hash/sha2/sha256.rs
  src/hazardous/hash/sha2/sha384.rs
  src/hazardous/hash/sha2/sha512.rs
  src/hazardous/kdf/argon2i.rs
  src/hazardous/mac/blake2b.rs
  src/hazardous/mac/hmac.rs
  src/hazardous/mac/mod.rs
  src/high_level/auth.rs
  src/high_level/hash.rs
  src/high_level/hltypes.rs
  src/high_level/kex.rs
  src/typedefs.rs
  tests/hash/mod.rs
Labels: breaking change

#230 Let seal_chunk take reference of StreamTag
  src/hazardous/aead/streaming.rs
  src/high_level/aead.rs
  tests/aead/pynacl_streaming_aead.rs
Labels: breaking change, hacktoberfest-accepted
