Repository orion-rs/orion, pull requests merged in 2022-01, with the labels that each got.

#268 Apply `clippy --tests` suggestions and add check to lints workflow
  .github/workflows/lints.yml
  CONTRIBUTING.md
  src/errors.rs
  src/hazardous/aead/streaming.rs
  src/hazardous/hash/sha2/mod.rs
  src/hazardous/hash/sha2/sha256.rs
  src/hazardous/hash/sha2/sha384.rs
  src/hazardous/hash/sha2/sha512.rs
  src/hazardous/kdf/argon2i.rs
  src/hazardous/kdf/pbkdf2.rs
  src/hazardous/mac/blake2b.rs
  src/hazardous/mac/hmac.rs
  src/hazardous/mac/poly1305.rs
  src/hazardous/stream/chacha20.rs
  src/high_level/auth.rs
  src/high_level/pwhash.rs
  tests/aead/mod.rs
  tests/aead/other_xchacha20_poly1305.rs
  tests/aead/pynacl_streaming_aead.rs
  tests/hash/blake2b_kat.rs
  tests/hash/mod.rs
  tests/kdf/custom_hkdf.rs
  tests/kdf/custom_pbkdf2.rs
  tests/kdf/other_argon2i.rs
  tests/kdf/other_hkdf.rs
  tests/kdf/ref_argon2i.rs
  tests/kdf/rfc_pbkdf2.rs
  tests/mac/mod.rs
  tests/mac/nist_cavp_hmac.rs
  tests/mac/other_poly1305.rs
  tests/mac/rfc_poly1305.rs
  tests/mod.rs
  tests/stream/mod.rs
Labels: testing, improvement

#228 impl standard IO traits for hashing
  src/hazardous/hash/blake2/blake2b.rs
  src/hazardous/hash/sha2/sha256.rs
  src/hazardous/hash/sha2/sha384.rs
  src/hazardous/hash/sha2/sha512.rs
  src/high_level/hash.rs
Labels: new feature

#260 fiat-crypto powered Poly1305
  Cargo.toml
  README.md
  src/hazardous/mac/poly1305.rs
Labels: improvement

#270 bench: Fix BLAKE2b benchmark
  benches/bench.rs
Labels: bugfix
